spring:
  datasource:
    url: jdbc:mysql://localhost:13311/hop
    username: mariadb
    password: mariadb
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30