spring:
  datasource:
    url: jdbc:mysql://localhost:13308/hop
    username: mariadb
    password: mariadb
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
#    store-type: redis
    store-type: jdbc
    jdbc:
      initialize-schema: always
#      initialize-schema: embedded
      schema: classpath:com/example/app/infrastructure/schema/db-session-schema.sql
      table-name: t01_connect_session
  redis:
    host: localhost
    port: 16379
    password: redis

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30