version: '3.1'
services:
  mysql:
    build: ./
    image: hop/account:0.1
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    container_name: hop-account
    ports:
    - "13318:3306"
    environment:
    - MYSQL_DATABASE=hop_account
    - MYSQL_USER=mariadb
    - MYSQL_PASSWORD=mariadb
    - MYSQL_ROOT_PASSWORD=root
